# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtGui import QIcon


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1085, 614)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMaximumSize(QtCore.QSize(1085, 16777215))
        MainWindow.setWindowIcon(QIcon("icon.png"))
        MainWindow.setStyleSheet("QTabWidget::pane { /* The tab widget frame */\n"
"    border-top: 2px solid #000000;\n"
"}\n"
"\n"
"QTabWidget::tab-bar {\n"
"    left: 5px; /* move to the right by 5px */\n"
"}\n"
"\n"
"/* Style the tab using the tab sub-control. Note that\n"
"    it reads QTabBar _not_ QTabWidget */\n"
"QTabBar::tab {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #000000);\n"
"    border: 2px solid #202020;\n"
"    border-bottom-color: #000000; /* same as the pane color */\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"    min-width: 8ex;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QTabBar::tab:selected, QTabBar::tab:hover {\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #a2a2a2);\n"
"}\n"
"\n"
"QTabBar::tab:selected {\n"
"    border-color: #9B9B9B;\n"
"    border-bottom-color: #C2C7CB; /* same as pane color */\n"
"}\n"
"\n"
"QTabBar::tab:!selected {\n"
"    margin-top: 2px; /* make non-selected tabs look smaller */\n"
"}\n"
"QMainWindow{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #000000);\n"
"}\n"
"QLabel, QFrame,QSplitter::handle,QSpinBox{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #000000);\n"
"}\n"
"QComboBox {\n"
"    border: 1px solid gray;\n"
"    border-radius: 3px;\n"
"    padding: 1px 18px 1px 3px;\n"
"    min-width: 6em;\n"
"}\n"
"\n"
"QComboBox:editable {\n"
"    background: lightgray;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    selection-background-color:#202020;\n"
"    color:#c8c8c8\n"
"}\n"
"\n"
"QComboBox:!editable, QComboBox::drop-down:editable {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #000000);\n"
"}\n"
"\n"
"/* QComboBox gets the \"on\" state when the popup is open */\n"
"QComboBox:!editable:on, QComboBox::drop-down:editable:on {\n"
"   background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #000000);\n"
"}\n"
"\n"
"QComboBox:on { /* shift the text when the popup opens */\n"
"    padding-top: 3px;\n"
"    padding-left: 4px;\n"
"}\n"
"\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: padding;\n"
"    subcontrol-position: top right;\n"
"    width: 15px;\n"
"\n"
"    border-left-width: 1px;\n"
"    border-left-color: darkgray;\n"
"    border-left-style: solid; /* just a single line */\n"
"    border-top-right-radius: 3px; /* same radius as the QComboBox */\n"
"    border-bottom-right-radius: 3px;\n"
"}\n"
"\n"
"QComboBox::down-arrow:on { /* shift the arrow when popup is open */\n"
"    top: 1px;\n"
"    left: 1px;\n"
"}\n"
"QPushButton{\n"
"    background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                stop: 0 #474747, stop: 0.4 #3d3d3d,\n"
"                                stop: 0.5 #333333, stop: 1.0 #000000);\n"
"}\n"
"QTabBar::tab, QLabel, QComboBox, QPushButton,QSpinBox{\n"
"     color:#c8c8c8\n"
"}\n"
"QMenuBar,QMenu{\n"
"    background:#474747;\n"
"    color:#c8c8c8\n"
"}\n"
"QMenu::item:selected {\n"
"    color:#6e6e6e\n"
"}\n"
"QPushButton::hover{\n"
"    Background:#6e6e6e;\n"
"}\n"
"QPushButton{\n"
"    border-radius: 1px\n"
"}\n"
"#filter_label, #freq_label, #kernel_label{\n"
"    background:#060606\n"
"}\n"
"QSpinBox, QSpinBox QAbstractItemView{\n"
"    border:0px;\n"
"    selection-background-color:#202020;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.main_widget = QtWidgets.QWidget(self.centralwidget)
        self.main_widget.setObjectName("main_widget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.main_widget)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.v_splitter = QtWidgets.QSplitter(self.main_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.v_splitter.sizePolicy().hasHeightForWidth())
        self.v_splitter.setSizePolicy(sizePolicy)
        self.v_splitter.setOrientation(QtCore.Qt.Vertical)
        self.v_splitter.setObjectName("v_splitter")
        self.widget_tabs = QtWidgets.QWidget(self.v_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_tabs.sizePolicy().hasHeightForWidth())
        self.widget_tabs.setSizePolicy(sizePolicy)
        self.widget_tabs.setObjectName("widget_tabs")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_tabs)
        self.gridLayout_2.setContentsMargins(9, 10, 13, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.h_spliter = QtWidgets.QSplitter(self.widget_tabs)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.h_spliter.sizePolicy().hasHeightForWidth())
        self.h_spliter.setSizePolicy(sizePolicy)
        self.h_spliter.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.h_spliter.setFrameShadow(QtWidgets.QFrame.Plain)
        self.h_spliter.setMidLineWidth(0)
        self.h_spliter.setOrientation(QtCore.Qt.Horizontal)
        self.h_spliter.setHandleWidth(11)
        self.h_spliter.setChildrenCollapsible(False)
        self.h_spliter.setObjectName("h_spliter")
        self.original_widget = QtWidgets.QTabWidget(self.h_spliter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(52)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.original_widget.sizePolicy().hasHeightForWidth())
        self.original_widget.setSizePolicy(sizePolicy)
        self.original_widget.setMinimumSize(QtCore.QSize(526, 534))
        self.original_widget.setMaximumSize(QtCore.QSize(351, 356))
        self.original_widget.setTabPosition(QtWidgets.QTabWidget.South)
        self.original_widget.setObjectName("original_widget")
        self.o_img_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_img_tab.sizePolicy().hasHeightForWidth())
        self.o_img_tab.setSizePolicy(sizePolicy)
        self.o_img_tab.setObjectName("o_img_tab")
        self.o_img_label = QtWidgets.QLabel(self.o_img_tab)
        self.o_img_label.setGeometry(QtCore.QRect(0, 0, 526, 534))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_img_label.sizePolicy().hasHeightForWidth())
        self.o_img_label.setSizePolicy(sizePolicy)
        self.o_img_label.setMinimumSize(QtCore.QSize(526, 534))
        self.o_img_label.setMaximumSize(QtCore.QSize(526, 534))
        self.o_img_label.setAutoFillBackground(False)
        self.o_img_label.setStyleSheet("#o_img_label{background:url(:/cat/1_1_526x534.png)}")
        self.o_img_label.setText("")
        self.o_img_label.setScaledContents(True)
        self.o_img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.o_img_label.setWordWrap(False)
        self.o_img_label.setObjectName("o_img_label")
        self.original_widget.addTab(self.o_img_tab, "")
        self.o_fourier_tab = QtWidgets.QWidget()
        self.o_fourier_tab.setObjectName("o_fourier_tab")
        self.o_fourier_label = QtWidgets.QLabel(self.o_fourier_tab)
        self.o_fourier_label.setGeometry(QtCore.QRect(0, 0, 526, 534))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_fourier_label.sizePolicy().hasHeightForWidth())
        self.o_fourier_label.setSizePolicy(sizePolicy)
        self.o_fourier_label.setMinimumSize(QtCore.QSize(526, 534))
        self.o_fourier_label.setMaximumSize(QtCore.QSize(526, 534))
        self.o_fourier_label.setAutoFillBackground(False)
        self.o_fourier_label.setText("")
        self.o_fourier_label.setScaledContents(True)
        self.o_fourier_label.setAlignment(QtCore.Qt.AlignCenter)
        self.o_fourier_label.setWordWrap(False)
        self.o_fourier_label.setObjectName("o_fourier_label")
        self.original_widget.addTab(self.o_fourier_tab, "")
        self.o_histogram_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_histogram_tab.sizePolicy().hasHeightForWidth())
        self.o_histogram_tab.setSizePolicy(sizePolicy)
        self.o_histogram_tab.setObjectName("o_histogram_tab")
        self.o_histogram_label = QtWidgets.QLabel(self.o_histogram_tab)
        self.o_histogram_label.setGeometry(QtCore.QRect(0, 0, 526, 534))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_histogram_label.sizePolicy().hasHeightForWidth())
        self.o_histogram_label.setSizePolicy(sizePolicy)
        self.o_histogram_label.setMinimumSize(QtCore.QSize(526, 534))
        self.o_histogram_label.setMaximumSize(QtCore.QSize(526, 534))
        self.o_histogram_label.setAutoFillBackground(False)
        self.o_histogram_label.setText("")
        self.o_histogram_label.setScaledContents(True)
        self.o_histogram_label.setAlignment(QtCore.Qt.AlignCenter)
        self.o_histogram_label.setWordWrap(False)
        self.o_histogram_label.setObjectName("o_histogram_label")
        self.original_widget.addTab(self.o_histogram_tab, "")
        self.edit_widget = QtWidgets.QTabWidget(self.h_spliter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.edit_widget.sizePolicy().hasHeightForWidth())
        self.edit_widget.setSizePolicy(sizePolicy)
        self.edit_widget.setMinimumSize(QtCore.QSize(526, 534))
        self.edit_widget.setTabPosition(QtWidgets.QTabWidget.South)
        self.edit_widget.setObjectName("edit_widget")
        self.e_img_tab = QtWidgets.QWidget()
        self.e_img_tab.setObjectName("e_img_tab")
        self.e_img_label = QtWidgets.QLabel(self.e_img_tab)
        self.e_img_label.setGeometry(QtCore.QRect(0, 0, 526, 534))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_img_label.sizePolicy().hasHeightForWidth())
        self.e_img_label.setSizePolicy(sizePolicy)
        self.e_img_label.setMinimumSize(QtCore.QSize(526, 534))
        self.e_img_label.setMaximumSize(QtCore.QSize(526, 534))
        self.e_img_label.setAutoFillBackground(False)
        self.e_img_label.setStyleSheet("#e_img_label{background:url(:/cat/1_1_526x534.png)}")
        self.e_img_label.setText("")
        self.e_img_label.setScaledContents(True)
        self.e_img_label.setAlignment(QtCore.Qt.AlignCenter)
        self.e_img_label.setWordWrap(False)
        self.e_img_label.setObjectName("e_img_label")
        self.edit_widget.addTab(self.e_img_tab, "")
        self.e_fourier_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_fourier_tab.sizePolicy().hasHeightForWidth())
        self.e_fourier_tab.setSizePolicy(sizePolicy)
        self.e_fourier_tab.setObjectName("e_fourier_tab")
        self.e_fourier_label = QtWidgets.QLabel(self.e_fourier_tab)
        self.e_fourier_label.setGeometry(QtCore.QRect(0, 0, 526, 534))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_fourier_label.sizePolicy().hasHeightForWidth())
        self.e_fourier_label.setSizePolicy(sizePolicy)
        self.e_fourier_label.setMinimumSize(QtCore.QSize(526, 534))
        self.e_fourier_label.setMaximumSize(QtCore.QSize(526, 534))
        self.e_fourier_label.setAutoFillBackground(False)
        self.e_fourier_label.setText("")
        self.e_fourier_label.setScaledContents(True)
        self.e_fourier_label.setAlignment(QtCore.Qt.AlignCenter)
        self.e_fourier_label.setWordWrap(False)
        self.e_fourier_label.setObjectName("e_fourier_label")
        self.edit_widget.addTab(self.e_fourier_tab, "")
        self.e_histogram_tab = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_histogram_tab.sizePolicy().hasHeightForWidth())
        self.e_histogram_tab.setSizePolicy(sizePolicy)
        self.e_histogram_tab.setObjectName("e_histogram_tab")
        self.e_histogram_label = QtWidgets.QLabel(self.e_histogram_tab)
        self.e_histogram_label .setGeometry(QtCore.QRect(0, 0, 526, 534))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_histogram_label .sizePolicy().hasHeightForWidth())
        self.e_histogram_label .setSizePolicy(sizePolicy)
        self.e_histogram_label .setMinimumSize(QtCore.QSize(526, 534))
        self.e_histogram_label .setMaximumSize(QtCore.QSize(526, 534))
        self.e_histogram_label .setAutoFillBackground(False)
        self.e_histogram_label .setText("")
        self.e_histogram_label .setScaledContents(True)
        self.e_histogram_label .setAlignment(QtCore.Qt.AlignCenter)
        self.e_histogram_label .setWordWrap(False)
        self.e_histogram_label .setObjectName("e_histogram_label ")
        self.edit_widget.addTab(self.e_histogram_tab, "")
        self.gridLayout_2.addWidget(self.h_spliter, 0, 0, 1, 1)
        self.options_widget = QtWidgets.QWidget(self.v_splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.options_widget.sizePolicy().hasHeightForWidth())
        self.options_widget.setSizePolicy(sizePolicy)
        self.options_widget.setMaximumSize(QtCore.QSize(16777215, 60))
        self.options_widget.setObjectName("options_widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.options_widget)
        self.verticalLayout.setContentsMargins(0, 0, 8, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.options_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setContentsMargins(14, 0, 0, 0)
        self.horizontalLayout.setSpacing(31)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.filter_label = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_label.sizePolicy().hasHeightForWidth())
        self.filter_label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.filter_label.setFont(font)
        self.filter_label.setStyleSheet("")
        self.filter_label.setScaledContents(False)
        self.filter_label.setObjectName("filter_label")
        self.horizontalLayout.addWidget(self.filter_label)
        self.filter_combobox = QtWidgets.QComboBox(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.filter_combobox.sizePolicy().hasHeightForWidth())
        self.filter_combobox.setSizePolicy(sizePolicy)
        self.filter_combobox.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.filter_combobox.setFont(font)
        self.filter_combobox.setObjectName("filter_combobox")
        self.filter_combobox.addItem("")
        self.filter_combobox.addItem("")
        self.filter_combobox.addItem("")
        self.filter_combobox.addItem("")
        self.horizontalLayout.addWidget(self.filter_combobox)
        self.freq_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.freq_label.setFont(font)
        self.freq_label.setObjectName("freq_label")
        self.horizontalLayout.addWidget(self.freq_label)
        self.freq_spinbox = QtWidgets.QSpinBox(self.widget)
        self.freq_spinbox.setAccelerated(True)
        self.freq_spinbox.setMaximum(100)
        self.freq_spinbox.setMinimum(1)
        self.freq_spinbox.setObjectName("freq_spinbox")
        self.horizontalLayout.addWidget(self.freq_spinbox)
        self.kernel_label = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.kernel_label.setFont(font)
        self.kernel_label.setObjectName("kernel_label")
        self.horizontalLayout.addWidget(self.kernel_label)
        self.kernel_spinbox = QtWidgets.QSpinBox(self.widget)
        self.kernel_spinbox.setAccelerated(True)
        self.kernel_spinbox.setMinimum(1)
        self.kernel_spinbox.setMaximum(31)
        self.kernel_spinbox.setSingleStep(2)
        self.kernel_spinbox.setObjectName("kernel_spinbox")
        self.horizontalLayout.addWidget(self.kernel_spinbox)
        self.equalize_btn = QtWidgets.QPushButton(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.equalize_btn.sizePolicy().hasHeightForWidth())
        self.equalize_btn.setSizePolicy(sizePolicy)
        self.equalize_btn.setMinimumSize(QtCore.QSize(80, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.equalize_btn.setFont(font)
        self.equalize_btn.setIconSize(QtCore.QSize(16, 16))
        self.equalize_btn.setDefault(False)
        self.equalize_btn.setFlat(False)
        self.equalize_btn.setObjectName("equalize_btn")
        self.horizontalLayout.addWidget(self.equalize_btn)
        self.verticalLayout.addWidget(self.widget)
        self.gridLayout_3.addWidget(self.v_splitter, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.main_widget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1085, 21))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExport = QtWidgets.QAction(MainWindow)
        self.actionExport.setObjectName("actionExport")
        self.menuFile.addAction(self.actionOpen)
        self.menuFile.addAction(self.actionExport)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.original_widget.setCurrentIndex(0)
        self.edit_widget.setCurrentIndex(0)
        self.filter_combobox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Filterio"))
        self.original_widget.setTabText(self.original_widget.indexOf(self.o_img_tab), _translate("MainWindow", "Original"))
        self.original_widget.setTabText(self.original_widget.indexOf(self.o_fourier_tab), _translate("MainWindow", "Fourier"))
        self.original_widget.setTabText(self.original_widget.indexOf(self.o_histogram_tab), _translate("MainWindow", "Histogram"))
        self.edit_widget.setTabText(self.edit_widget.indexOf(self.e_img_tab), _translate("MainWindow", "Edited"))
        self.edit_widget.setTabText(self.edit_widget.indexOf(self.e_fourier_tab), _translate("MainWindow", "Fourier"))
        self.edit_widget.setTabText(self.edit_widget.indexOf(self.e_histogram_tab), _translate("MainWindow", "Histogram"))
        self.filter_label.setText(_translate("MainWindow", "Choose Filter :"))
        self.filter_combobox.setItemText(0, _translate("MainWindow", "Low Pass Filter"))
        self.filter_combobox.setItemText(1, _translate("MainWindow", "High Pass Filter"))
        self.filter_combobox.setItemText(2, _translate("MainWindow", "Median Filter"))
        self.filter_combobox.setItemText(3, _translate("MainWindow", "Laplacian Filter "))
        self.freq_label.setText(_translate("MainWindow", "Filter Radius:"))
        self.kernel_label.setText(_translate("MainWindow", "Kernel Size:"))
        self.equalize_btn.setText(_translate("MainWindow", "Equalize"))
        self.menuFile.setTitle(_translate("MainWindow", "File"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionExport.setText(_translate("MainWindow", "Export"))






if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
